name:       carma-models
version:    0.41.0
synopsis:   Model definitions/CRUD for CaRMa
license:    MIT
author:     Formal Methods
maintainer: dev@formalmethods.ru
category:   Database


dependencies:
 - aeson
 - base
 - base16-bytestring
 - blaze-builder
 - blaze-textual
 - bytestring
 - carma-utils
 - cereal
 - containers
 - errors
 - parsec
 - persistent
 - persistent-template
 - postgresql-libpq
 - postgresql-simple
 - qm-interpolated-string
 - scientific
 - singletons
 - template-haskell
 - text
 - time
 - transformers
 - unordered-containers
 - vector

default-extensions:
 - DataKinds
 - KindSignatures
 - TypeOperators
 - TypeFamilies
 - EmptyDataDecls
 - MultiParamTypeClasses
 - FlexibleInstances
 - FlexibleContexts
 - DeriveDataTypeable
 - OverloadedStrings
 - TupleSections
 - NamedFieldPuns
 - RecordWildCards
 - LambdaCase

ghc-options:
  - -Wall
  - -Werror
  - -O2
  - -funbox-strict-fields

library:
  source-dirs: src
