resolver: lts-15.15

packages:
- srv
- tools/vinnie
- tools/carma-configurator
- caroperator-svc
- carma-utils
- carma-models
- carma-model-utils
- carma-monads
- carma-http
- carma-dict
- carma-mobile-server
- carma-nominatim-mediator
- carma-era-glonass-integration
- location-sharing-svc

allow-newer: true

extra-deps:
- attoparsec-conduit-1.1.0
- digestive-functors-0.8.2.0
- digestive-functors-heist-0.8.7.0
- digestive-functors-snap-0.7.0.0
- heist-1.1.0.1
- map-syntax-0.3
- pwstore-fast-2.4.4
- snap-1.1.3.0
- snap-loader-static-1.0.0.0
- snaplet-postgresql-simple-1.2.0.0
- stm-lifted-2.5.0.0
- xmlhtml-0.2.5.2
- git: https://github.com/ruamk/dmcc.git
  commit: afdc7aefdddb644cdcdcfa69262129b698493f04
- git: https://github.com/ruamk/hs-weather-api.git
  commit: 598e511b6aa088e6800a8c9e668d76c388d544de
- git: https://github.com/ruamk/pg-simple-alt-qq.git
  commit: 15fd5b959f0d88a50d2c460938bdb0cd2cd7322d
- git: https://github.com/ruamk/websockets-snap.git
  commit: 8316c620bf4ffae8e6777e0b368edd0ce32a4324
- git: https://github.com/Soostone/snaplet-persistent.git
  commit: ceb82af6c4305eeca2c9e5fe06982d623021da48
