* Планирование
  Перед принятием решения о релизе необходимо определиться со списком
  функционала, который попадет в релиз.

* Разработка
  Разработчики пишут необходимые для релиза фичи, периодически показывая
  их тестерам. Подготовка длится до тех пор, пока разработчики и тестеры
  не будут считать, что необходимый для релиза функционал (без учета
  багов) реализован, находится в ветке `master` и готов к использованию
  в тестовом окружении.

* Подготовка
  На этот пункт должно быть отведено около 5 дней.

** Feature freeze
   Когда все необзодимое для релиза написано ветка `master`
   замораживается для новых фич, с этого момента допустимо пушить в нее
   только фиксы багов, которые необходимо поправить до релиза.

** ОА проверяет основной процесс + функционал запланированый к релизу.
   Если обнружены баги, по ним создаются тикеты и отдаются
   разработчикам. Итерация повторяется, пока не будут исправлены все
   баги, блокирующие релиз.

** Назначается ответственный из аналитиков (ОА) и разработчиков (ОР)

** Назначается дата релиза
   Когда баги исправлены, назначается дата релиза (в данный момент мастер
   будет достаточно стабильным, так что можно дату релиза выбирать
   пораньше). В календаре создается событие на дату релиза.

* Релиз
** ОА за час предупреждает всех (ramc@ruamc.ru) о релизе
** ОР проводит релиз

* Поиск невиновных и награждение непричастных

** Если после релиза ошибки найдены в основном процессе или в
   функционале указанном разработчиками - это ответственность ОА

** Если после релиза ошибки найдены в других процессах, то
   ответственность на разработчике, в чьей зоне ответственности лежит
   этот функционал и в следующий раз он ОР.
