# dependencies that goes to 'resources' bundle

require "carma-tpl/fields/form.pug"
require "carma-tpl/fields/ro.pug"
require "carma-tpl/fields/table.pug"

require "carma-tpl/lib/navbar.pug"

require "carma-tpl/partials/partnerDelayDialog.pug"
require "carma-tpl/partials/partnersSearch.pug"
require "carma-tpl/partials/navbar.pug"
require "carma-tpl/partials/topLevelModals.pug"

require "carma-tpl/screens/kpi/group.pug"
require "carma-tpl/screens/kpi/oper.pug"
require "carma-tpl/screens/kpi/stat.pug"
require "carma-tpl/screens/back.pug"
require "carma-tpl/screens/call.pug"
require "carma-tpl/screens/case.pug"
require "carma-tpl/screens/contract.pug"
require "carma-tpl/screens/dictionaries.pug"
require "carma-tpl/screens/na.pug"
require "carma-tpl/screens/partner.pug"
require "carma-tpl/screens/partnersSearch.pug"
require "carma-tpl/screens/printSrv.pug"
require "carma-tpl/screens/processingConfig.pug"
require "carma-tpl/screens/rest.pug"
require "carma-tpl/screens/rkc.pug"
require "carma-tpl/screens/search.pug"
require "carma-tpl/screens/serviceBreak.pug"
require "carma-tpl/screens/supervisor.pug"
require "carma-tpl/screens/timeline.pug"
require "carma-tpl/screens/uploads.pug"
require "carma-tpl/screens/vin.pug"

require "carma/neoComponents/SmsForm/template.pug"
require "carma/neoComponents/AvarcomTasks/template.pug"
require "carma/neoComponents/DiagTree/Show/template.pug"
require "carma/neoComponents/DiagTree/Show/Inside/template.pug"
require "carma/neoComponents/DiagTree/Editor/template.pug"
require "carma/neoComponents/DiagTree/Editor/Inside/template.pug"
require "carma/neoComponents/PermissionBlock/template.pug"

# OpenLayers 3p images
require "ol2/img/blank.gif"
require "ol2/img/cloud-popup-relative.png"
require "ol2/img/drag-rectangle-off.png"
require "ol2/img/drag-rectangle-on.png"
require "ol2/img/east-mini.png"
require "ol2/img/layer-switcher-maximize.png"
require "ol2/img/layer-switcher-minimize.png"
require "ol2/img/marker-blue.png"
require "ol2/img/marker-gold.png"
require "ol2/img/marker-green.png"
require "ol2/img/marker.png"
require "ol2/img/measuring-stick-off.png"
require "ol2/img/measuring-stick-on.png"
require "ol2/img/north-mini.png"
require "ol2/img/panning-hand-off.png"
require "ol2/img/panning-hand-on.png"
require "ol2/img/slider.png"
require "ol2/img/south-mini.png"
require "ol2/img/west-mini.png"
require "ol2/img/zoom-minus-mini.png"
require "ol2/img/zoom-plus-mini.png"
require "ol2/img/zoom-world-mini.png"
require "ol2/img/zoombar.png"
