# dependencies that goes to 'resources' bundle

require "carma-tpl/fields/form.pug"
require "carma-tpl/fields/ro.pug"
require "carma-tpl/fields/table.pug"

require "carma-tpl/lib/navbar.pug"

require "carma-tpl/partials/partnerDelayDialog.pug"
require "carma-tpl/partials/partnersSearch.pug"
require "carma-tpl/partials/navbar.pug"
require "carma-tpl/partials/topLevelModals.pug"

require "carma-tpl/screens/kpi/group.pug"
require "carma-tpl/screens/kpi/oper.pug"
require "carma-tpl/screens/kpi/stat.pug"
require "carma-tpl/screens/back.pug"
require "carma-tpl/screens/call.pug"
require "carma-tpl/screens/case.pug"
require "carma-tpl/screens/contract.pug"
require "carma-tpl/screens/dictionaries.pug"
require "carma-tpl/screens/na.pug"
require "carma-tpl/screens/partner.pug"
require "carma-tpl/screens/partnersSearch.pug"
require "carma-tpl/screens/printSrv.pug"
require "carma-tpl/screens/processingConfig.pug"
require "carma-tpl/screens/rest.pug"
require "carma-tpl/screens/rkc.pug"
require "carma-tpl/screens/search.pug"
require "carma-tpl/screens/serviceBreak.pug"
require "carma-tpl/screens/supervisor.pug"
require "carma-tpl/screens/timeline.pug"
require "carma-tpl/screens/uploads.pug"
require "carma-tpl/screens/vin.pug"

require "carma/neoComponents/SmsForm/template.pug"
