DELETE FROM "FieldPermission"
WHERE model in
   ( 'case'
   , 'call'
   , 'averageCommissioner'
   , 'bank'
   , 'consultation'
   , 'continue'
   , 'deliverCar'
   , 'deliverParts'
   , 'hotel'
   , 'information'
   , 'ken'
   , 'rent'
   , 'service'
   , 'sober'
   , 'taxi'
   , 'tech'
   , 'tech1'
   , 'tickets'
   , 'towage'
   , 'transportation'
   , 'usermeta'
   );
