DROP INDEX "Contract_coalesce_idx";
DROP INDEX "Contract_coalesce_idx1";
DROP INDEX "Contract_coalesce_idx10";
DROP INDEX "Contract_coalesce_idx11";
DROP INDEX "Contract_coalesce_idx12";
DROP INDEX "Contract_coalesce_idx13";
DROP INDEX "Contract_coalesce_idx14";
DROP INDEX "Contract_coalesce_idx15";
DROP INDEX "Contract_coalesce_idx16";
DROP INDEX "Contract_coalesce_idx17";
DROP INDEX "Contract_coalesce_idx18";
DROP INDEX "Contract_coalesce_idx19";
DROP INDEX "Contract_coalesce_idx2";
DROP INDEX "Contract_coalesce_idx20";
DROP INDEX "Contract_coalesce_idx21";
DROP INDEX "Contract_coalesce_idx22";
DROP INDEX "Contract_coalesce_idx23";
DROP INDEX "Contract_coalesce_idx24";
DROP INDEX "Contract_coalesce_idx3";
DROP INDEX "Contract_coalesce_idx4";
DROP INDEX "Contract_coalesce_idx5";
DROP INDEX "Contract_coalesce_idx6";
DROP INDEX "Contract_coalesce_idx7";
DROP INDEX "Contract_coalesce_idx8";
DROP INDEX "Contract_coalesce_idx9";


CREATE INDEX ON "Contract" (name);
CREATE INDEX ON "Contract" (email);
CREATE INDEX ON "Contract" (vin);
CREATE INDEX ON "Contract" (cardNumber);
CREATE INDEX ON "Contract" (codeWord);
CREATE INDEX ON "Contract" (phone);
CREATE INDEX ON "Contract" (plateNum);
CREATE INDEX ON "Contract" (validSince);
CREATE INDEX ON "Contract" (validUntil);
CREATE INDEX ON "Contract" (startMileage);
CREATE INDEX ON "Contract" (make);
CREATE INDEX ON "Contract" (model);
CREATE INDEX ON "Contract" (makeYear);
CREATE INDEX ON "Contract" (carClass);
CREATE INDEX ON "Contract" (color);
CREATE INDEX ON "Contract" (transmission);
CREATE INDEX ON "Contract" (engineVolume);
CREATE INDEX ON "Contract" (engineType);
CREATE INDEX ON "Contract" (buyDate);
CREATE INDEX ON "Contract" (seller);
CREATE INDEX ON "Contract" (lastCheckDealer);
CREATE INDEX ON "Contract" (checkPeriod);
CREATE INDEX ON "Contract" (checkType);
CREATE INDEX ON "Contract" (orderNumber);
CREATE INDEX ON "Contract" (managerName);
CREATE INDEX ON "Contract" (comment);
CREATE INDEX ON "Contract" (legalForm);
CREATE INDEX ON "Contract" (subprogram);
