ALTER TABLE servicetbl DROP COLUMN assignedTo;

ALTER TABLE averagecommissionertbl DROP COLUMN assignedTo;
ALTER TABLE banktbl DROP COLUMN assignedTo;
ALTER TABLE consultationtbl DROP COLUMN assignedTo;
ALTER TABLE continuetbl DROP COLUMN assignedTo;
ALTER TABLE delivercartbl DROP COLUMN assignedTo;
ALTER TABLE deliverclienttbl DROP COLUMN assignedTo;
ALTER TABLE deliverpartstbl DROP COLUMN assignedTo;
ALTER TABLE hoteltbl DROP COLUMN assignedTo;
ALTER TABLE informationtbl DROP COLUMN assignedTo;
ALTER TABLE kentbl DROP COLUMN assignedTo;
ALTER TABLE renttbl DROP COLUMN assignedTo;
ALTER TABLE sobertbl DROP COLUMN assignedTo;
ALTER TABLE taxitbl DROP COLUMN assignedTo;
ALTER TABLE techtbl DROP COLUMN assignedTo;
ALTER TABLE ticketstbl DROP COLUMN assignedTo;
ALTER TABLE towagetbl DROP COLUMN assignedTo;
ALTER TABLE transportationtbl DROP COLUMN assignedTo
