update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 75;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 108;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 109;
update "Program" set shortLabel = 'InTouch Помощь на дорогах' where id = 31;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 47;
update "Program" set shortLabel = 'КИА Центр Кемерово помощь на дорогах' where id = 248;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 187;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 105;
update "Program" set shortLabel = 'Skoda Assistance' where id = 257;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 56;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 51;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 60;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 50;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 63;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 144;
update "Program" set shortLabel = 'Haval Assistance' where id = 73;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 154;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 194;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 270;
update "Program" set shortLabel = 'DFM Assistance' where id = 213;
update "Program" set shortLabel = 'Автокласс Ассистанс' where id = 199;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 62;
update "Program" set shortLabel = 'Citroen Assistance' where id = 67;
update "Program" set shortLabel = 'Peugeot Assistance' where id = 1;
update "Program" set shortLabel = 'Автопилот − Помощь на дорогах' where id = 241;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 64;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 58;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 78;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 130;
update "Program" set shortLabel = 'Программа закрыта' where id = 203;
update "Program" set shortLabel = 'DS Assistance' where id = 214;
update "Program" set shortLabel = 'АСПЭК-Драйв помощь на дорогах' where id = 246;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 217;
update "Program" set shortLabel = 'Горячая линия Arval' where id = 157;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 192;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 15;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 189;
update "Program" set shortLabel = 'BMW Roadside Assistance' where id = 171;
update "Program" set shortLabel = 'Arval Assistance' where id = 110;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 215;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 249;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 195;
update "Program" set shortLabel = 'АвтоБелогорье помощь на дорогах' where id = 218;
update "Program" set shortLabel = 'Белый Сервис − Помощь на дорогах' where id = 244;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 280;
update "Program" set shortLabel = 'Гарантия мобильности Volkswagen' where id = 252;
update "Program" set shortLabel = 'CARCADE Помощь на дороге' where id = 262;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 269;
update "Program" set shortLabel = 'Zotye Уверенность' where id = 245;
update "Program" set shortLabel = 'ТулаАвтоСервис помощь на дорогах' where id = 247;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 271;
update "Program" set shortLabel = 'Аренда-Авто. Помощь на дорогах' where id = 66;
update "Program" set shortLabel = 'RAMC Roadside Assistance' where id = 30;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 80;
update "Program" set shortLabel = 'KADET ASSISTANCE − помощь на дорогах' where id = 242;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 272;
update "Program" set shortLabel = 'Аларм−Моторс. Помощь на дорогах' where id = 216;
update "Program" set shortLabel = 'GM Assistance' where id = 4;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 263;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 277;
update "Program" set shortLabel = 'WAY+' where id = 240;
update "Program" set shortLabel = 'BMW Roadside Assistance' where id = 177;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 149;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 281;
update "Program" set shortLabel = 'Bentley Assistance' where id = 22;
update "Program" set shortLabel = 'Rolls-Royce Roadside Assistance' where id = 179;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 44;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 76;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 77;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 132;
update "Program" set shortLabel = 'Гарантия мобильности Mazda' where id = 143;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 126;
update "Program" set shortLabel = 'DKV ASSIST' where id = 124;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 273;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 161;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 159;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 220;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 278;
update "Program" set shortLabel = 'KADET ASSISTANCE − помощь на дорогах' where id = 264;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 282;
update "Program" set shortLabel = 'Нижегородец Помощь на дорогах' where id = 204;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 205;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 221;
update "Program" set shortLabel = 'Ренессанс помощь на дорогах' where id = 223;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 227;
update "Program" set shortLabel = 'Автовист. Помощь на дорогах' where id = 228;
update "Program" set shortLabel = 'WILLZ помощь на дорогах' where id = 232;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 265;
update "Program" set shortLabel = 'СТК Центр. Помощь на дорогах' where id = 229;
update "Program" set shortLabel = 'Нижегородец Помощь на дорогах' where id = 230;
update "Program" set shortLabel = 'Audi Помощь на дорогах' where id = 256;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 287;
update "Program" set shortLabel = 'Аларм. Помощь на дорогах' where id = 5;
update "Program" set shortLabel = 'Помощь на дорогах' where id = 185;
update "Program" set shortLabel = 'Автоэксклюзив. Помощь на дорогах' where id = 225;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 151;
update "Program" set shortLabel = 'Opel Assistance' where id = 284;
update "Program" set shortLabel = 'Авторитет Ассистанс' where id = 207;
update "Program" set shortLabel = 'Авторезерв Ассистанс' where id = 224;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 279;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 286;
update "Program" set shortLabel = 'Changan помощь на дорогах' where id = 289;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 226;
update "Program" set shortLabel = 'Автомама − помощь на дорогах' where id = 236;
update "Program" set shortLabel = 'Румос Авто − Помощь на дорогах' where id = 266;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 258;
update "Program" set shortLabel = 'Ducati Помощь на дорогах' where id = 285;
update "Program" set shortLabel = 'Europlan Assistance' where id = 276;
update "Program" set shortLabel = 'Норд Авто − Помощь на дорогах' where id = 267;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 134;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 211;
update "Program" set shortLabel = 'Тринити Моторс Ассистанс' where id = 202;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 210;
update "Program" set shortLabel = 'СеулАвтоТула помощь на дорогах' where id = 259;
update "Program" set shortLabel = 'Автоброкер Ассистанс' where id = 209;
update "Program" set shortLabel = 'KADET ASSISTANCE − помощь на дорогах' where id = 261;
update "Program" set shortLabel = 'KIA помощь на дорогах' where id = 8;
update "Program" set shortLabel = 'Энитайм Прайм − Помощь на дорогах' where id = 268;
update "Program" set shortLabel = 'РАМК Помощь на дорогах' where id = 290;
