UPDATE renttbl SET carClass = '1' WHERE lower(carClass)='a';
UPDATE renttbl SET carClass = '2' WHERE lower(carClass)='b';
UPDATE renttbl SET carClass = '3' WHERE lower(carClass)='c';
UPDATE renttbl SET carClass = '4' WHERE lower(carClass)='d';
UPDATE renttbl SET carClass = '5' WHERE lower(carClass)='e';
UPDATE renttbl SET carClass = '6' WHERE lower(carClass)='f';
UPDATE renttbl SET carClass = '7' WHERE lower(carClass)='psab';
UPDATE renttbl SET carClass = '8' WHERE lower(carClass)='psam1';
UPDATE renttbl SET carClass = '9' WHERE lower(carClass)='psam2';
