ALTER TABLE "ServiceNames" DROP COLUMN IF EXISTS fdds;
ALTER TABLE "ServiceNames" ADD COLUMN fdds text;

ALTER TABLE "Program" DROP COLUMN IF EXISTS fdds;
ALTER TABLE "Program" ADD COLUMN fdds text;

ALTER TABLE "CarMake" DROP COLUMN IF EXISTS fdds;
ALTER TABLE "CarMake" ADD COLUMN fdds text;

ALTER TABLE "CarModel" DROP COLUMN IF EXISTS fdds;
ALTER TABLE "CarModel" ADD COLUMN fdds text;

ALTER TABLE "System" DROP COLUMN IF EXISTS fdds;

ALTER TABLE "Part" DROP COLUMN IF EXISTS fdds;
ALTER TABLE "Part" ADD COLUMN fdds text;

ALTER TABLE "Cause" DROP COLUMN IF EXISTS fdds;
ALTER TABLE "Cause" ADD COLUMN fdds text;

ALTER TABLE "Suggestion" DROP COLUMN IF EXISTS fdds;
